version: '3.8'
services:
  menu_api:
    container_name: menu_api
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=menu_api